### ISSUE TITLE
Upgrade production site to Elgg 2

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/sbw#45]
## Warm up phase:

- [x] check and accept :) Michele's PR for added/deleted plugins [here](https://github.com/sbwtech/sbw/pull/50) (@juho-jaakkola)
- [x] check and accept :) Luca's PRs for theme (@juho-jaakkola)
- [x] setup old.internal.socialbusinessworld.org domain + db + script (@feroda)
- [x] upgrade the Debian system (@feroda)
- [x] upgrade Plesk (@feroda)

# Steps:

1. Prepare Elgg 2 version
 - [x] Checkout the code to a temporary directory and run `composer install`
 - [x] Copy `settings.php` content from production
 - [x] Copy possible `.htaccess` configuration from production
2. Put site to Maintenance mode and disable cache (@michelesbw)
3. Make backups of existing data (@feroda)
 - [x] sync old.internal.socialbusinessworld.org
 - [x] Database
 - [x] Dataroot
 - [x] Copy etherpad contents manually (@michelesbw) - NOTE: @feroda keep the content on your server, I have aready copied the remaining info (owner, group, link, access level, description)
4. Prerequisites for code upgrade (@juho-jaakkola):
 - [x] Make sure `.gitignore` is the latest version (checkout it separately)
 - [x] Use `git reset --hard upstream/1.9` to get latest `1.9` code
 - [x] Upgrade `profile_manager` to version `v.9.0` (current doesn't work with Elgg `1.10`)
 - [x] Disable all plugins that will not be used in Elgg 2
5. Upgrade to each Elgg `1.x` version at a time (@juho-jaakkola):
 - [x] Disable plugins with `mod/disabled` file
 - [x] Checkout the correct version
 - [x] Run `composer install`
 - [x] Run `upgrade.php` and possible async upgrades
 - [x] Enable plugins by removing the `mod/disabled` file
 - [x] Run `upgrade.php` and possible async upgrades again for plugins
6. Once on Elgg `1.12` switch to Elgg 2 code (@juho-jaakkola)
 - [x] Run the previous commands once again
7. [x] Reorder plugins (@michelesbw)
8. Update etherpad contents (@michelesbw)
 - [x] Enter plugin settings
 - [x] Use `login_as` feature to copy-paste etherpad contents from old plugin to the new one
9. Application settings checks/upgrades (@michelesbw):
 - [x] copy/paste relevant settings/values AND (sub)folders ("images") and files from old.internal.socialbusinessworld.org
 - [x] Check upgrades section https://socialbusinessworld.org/admin/upgrades
 - [x] groups map 1. change the name of field "grouplocation" to location in profile manager plugin - 2. run the script in  "Groups Geolocation" at plugin settings
 - [x] settings: new setting for default number of items per page https://socialbusinessworld.org/admin/settings/basic
 - [x] check if all new Ismayil's plugins have been added (discovery, discussions, inbox, interactions, invite, ui_responsive_tabs, ui_tabs, lists)
 - [x] check maps settings here https://socialbusinessworld.org/admin/settings/amap_maps_api AND https://socialbusinessworld.org/admin/settings/groupsmap AND https://beta.socialbusinessworld.org/admin/settings/membersmap
 - [x] Check all needed crons exists for plugins and core using them
 - [x] check decision about ckeditor extended. If in use then check HTMLawed plugin's settings. Otherwise use Ismayil's https://github.com/hypeJunction/Elgg-ckeditor_addons
 - [x] Set "Should the FAQ site menu entry be visible when not logged in?" on YES here https://socialbusinessworld.org/admin/plugin_settings/faq
 - [x] Set on YES "Should logged-out site visitors be allowed to give feedback? here https://beta.socialbusinessworld.org/admin/plugin_settings/feedback
 - [x] Check html emails (notifications) layout and NEW SETTINGS (-f notifications@socialbusinessworld.org) here https://socialbusinessworld.org/admin/plugin_settings/html_email_handler
 - [x] Check poll settings
 - [x] Check RSS Import settings https://socialbusinessworld.org/admin/plugin_settings/rssimport
 - [x] Change Site menu entry forwards to: Photo albums here https://socialbusinessworld.org/admin/settings/photos AND remaining Tidypics settings
 - [x] enable "Use symbolic link to simple cache directory" after server check in /admin/settings/advanced
 - [x] CHECK TRANSLATIONS IN ITALIAN (copy "old" production translations into new production translations first data/translation_editor/ and then upload new plugins' translations -> ANNOUNCEMENT TO TRANSLATOR GROUP

## Expected results (to be checked at the end)

- [x] `old.internal.socialbusinessworld.org` -> the old (present) production site
- [x] `www.socialbusinessworld.org` -> production site -> prod_sbw in the current state of the beta
- [x] `beta.socialbusinessworld.org` -> copy of the production site. Used for staging -> beta_sbw

## BONUS (alltogether!)

@feroda do, @juho-jaakkola checks/helps checking tech parts and doc refs, @michelesbw user checks
If all is gone well and we have time do some more improvements, we can try:

- [x] nginx + php7 (or at least nginx + php-fpm)
- [x] memcached

**Comment by michelesbw** [comment]
- [ ] make a backup copy of current site (preug.socialbusinessworld.org ?) to then copy/paste relevant settings/values

- [ ] Check upgrades section https://socialbusinessworld.org/admin/upgrades

- [ ] groups map 1. change the name of field "grouplocation" to location in profile manager plugin - 2. run the script in  "Groups Geolocation" at plugin settings

- [ ] settings: new setting for default number of items per page https://socialbusinessworld.org/admin/settings/basic

- [ ] check maps settings here https://socialbusinessworld.org/admin/settings/amap_maps_api AND https://socialbusinessworld.org/admin/settings/groupsmap AND https://beta.socialbusinessworld.org/admin/settings/membersmap

- [ ] Check all needed crons exists for plugins and core using them

- [ ] check decision about ckeditor extended. If in use then check HTMLawed plugin's settings. Otherwise use Ismayil's https://github.com/hypeJunction/Elgg-ckeditor_addons

- [ ] Set "Should the FAQ site menu entry be visible when not logged in?" on YES here https://socialbusinessworld.org/admin/plugin_settings/faq

- [ ] Check html emails (notifications) layout and settings (-f notifications@socialbusinessworld.org) here https://socialbusinessworld.org/admin/plugin_settings/html_email_handler

- [ ] Check poll settings

- [ ] Check RSS Import settings https://socialbusinessworld.org/admin/plugin_settings/rssimport

- [ ] Change Site menu entry forwards to: Photo albums here https://socialbusinessworld.org/admin/settings/photos AND remaining Tidypics settings

**Comment by feroda** [comment]
at the end we have:

- [ ] old.internal.socialbusinessworld.org -> the old (present) production site
- [ ] www.socialbusinessworld.org -> production site
- [ ] beta.socialbusinessworld.org -> copy of the production site. Used for staging

let's do it all, and if we do it fast, we can give some time to giva a chance to nginx + php7

monday is a great day guys!

**Comment by feroda** [comment]
sorting and assignments in https://github.com/sbwtech/sbw/wiki/Upgrade-production-site-to-Elgg-2

**Comment by feroda** [comment]
The final list (the wiki page is no chekkable ;))

## Warm up phase:

- [ ] check and accept :) Michele's PR for added/deleted plugins [here](https://github.com/sbwtech/sbw/pull/50) (@juho-jaakkola)
- [ ] check and accept :) Luca's PRs for theme (@juho-jaakkola)
- [ ] setup old.internal.socialbusinessworld.org domain + db + script (@feroda)
- [ ] upgrade the Debian system (@feroda)
- [ ] upgrade Plesk (@feroda)

# Steps:

1. Prepare Elgg 2 version
 - [ ] Checkout the code to a temporary directory and run `composer install`
 - [ ] Copy `settings.php` content from production
 - [ ] Copy possible `.htaccess` configuration from production
2. Put site to Maintenance mode and disable cache (@michelesbw)
3. Make backups of existing data (@feroda)
 - [ ] sync old.internal.socialbusinessworld.org
 - [ ] Database
 - [ ] Dataroot
 - [ ] Copy etherpad contents manually (@michelesbw) - NOTE: @feroda keep the content on your server, I have aready copied the remaining info (owner, group, link, access level, description)
4. Prerequisites for code upgrade (@juho-jaakkola):
 - [ ] Make sure `.gitignore` is the latest version (checkout it separately)
 - [ ] Use `git reset --hard upstream/1.9` to get latest `1.9` code
 - [ ] Upgrade `profile_manager` to version `v.9.0` (current doesn't work with Elgg `1.10`)
 - [ ] Disable all plugins that will not be used in Elgg 2
5. Upgrade to each Elgg `1.x` version at a time (@juho-jaakkola):
 - Disable plugins with `mod/disabled` file
 - Checkout the correct version
 - Run `composer install`
 - Run `upgrade.php` and possible async upgrades
 - Enable plugins by removing the `mod/disabled` file
 - Run `upgrade.php` and possible async upgrades again for plugins
6. Once on Elgg `1.12` switch to Elgg 2 code (@juho-jaakkola)
 - Run the previous commands once again
7. Reorder plugins (@michelesbw)
8. Update etherpad contents (@michelesbw)
 - [ ] Enter plugin settings
 - [ ] Use `login_as` feature to copy-paste etherpad contents from old plugin to the new one
9. Application settings checks/upgrades (@michelesbw):
 - [ ] copy/paste relevant settings/values AND (sub)folders ("images") and files from old.internal.socialbusinessworld.org
 - [ ] Check upgrades section https://socialbusinessworld.org/admin/upgrades
 - [ ] groups map 1. change the name of field "grouplocation" to location in profile manager plugin - 2. run the script in  "Groups Geolocation" at plugin settings
 - [ ] settings: new setting for default number of items per page https://socialbusinessworld.org/admin/settings/basic
 - [ ] check if all new Ismayil's plugins have been added (discovery, discussions, inbox, interactions, invite, ui_responsive_tabs, ui_tabs, lists)
 - [ ] check maps settings here https://socialbusinessworld.org/admin/settings/amap_maps_api AND https://socialbusinessworld.org/admin/settings/groupsmap AND https://beta.socialbusinessworld.org/admin/settings/membersmap
 - [ ] Check all needed crons exists for plugins and core using them
 - [ ] check decision about ckeditor extended. If in use then check HTMLawed plugin's settings. Otherwise use Ismayil's https://github.com/hypeJunction/Elgg-ckeditor_addons
 - [ ] Set "Should the FAQ site menu entry be visible when not logged in?" on YES here https://socialbusinessworld.org/admin/plugin_settings/faq
 - [ ] Set on YES "Should logged-out site visitors be allowed to give feedback? here https://beta.socialbusinessworld.org/admin/plugin_settings/feedback
 - [ ] Check html emails (notifications) layout and NEW SETTINGS (-f notifications@socialbusinessworld.org) here https://socialbusinessworld.org/admin/plugin_settings/html_email_handler
 - [ ] Check poll settings
 - [ ] Check RSS Import settings https://socialbusinessworld.org/admin/plugin_settings/rssimport
 - [ ] Change Site menu entry forwards to: Photo albums here https://socialbusinessworld.org/admin/settings/photos AND remaining Tidypics settings
 - [ ] enable "Use symbolic link to simple cache directory" after server check in /admin/settings/advanced
 - [ ] CHECK TRANSLATIONS IN ITALIAN (copy "old" production translations into new production translations first data/translation_editor/ and then upload new plugins' translations -> ANNOUNCEMENT TO TRANSLATOR GROUP

## Expected results (to be checked at the end)

- [ ] `old.internal.socialbusinessworld.org` -> the old (present) production site
- [ ] `www.socialbusinessworld.org` -> production site -> prod_sbw in the current state of the beta
- [ ] `beta.socialbusinessworld.org` -> copy of the production site. Used for staging -> beta_sbw

## BONUS (alltogether!)

@feroda do, @juho-jaakkola checks/helps checking tech parts and doc refs, @michelesbw user checks
If all is gone well and we have time do some more improvements, we can try:

- [ ] nginx + php7 (or at least nginx + php-fpm)
- [ ] memcached

**Comment by michelesbw** [comment]
Ok here's my update/errors seen/reminder:

- could not reorder plugins because old.* was not reachable;

- have to check for files/folders in main dir for manual import (old stuff still needed not Elgg's but needed)

- ERRORS 'elgg_entity_geometry' has been populated with information about the location of 0 entities; geographic coordinates for 50 entities were incorrect MAYBE AFTER MAP OF GROUPS GEOLOCATION SCRIPT

- ERROR Due to your server configuration the symbolic link can not be established automatically. Please refer to the documentation and establish the symbolic link manually.

- River addon plugin seems missing also in composer. MUCH needed

- Pads' link is not shown in sub-groups side menu even if enabled

- plugins settings need to be double-checked once old is back fully functional

- all remaining plugins in my PR are needed

- translations for italian language need to be completed
